### ISSUE TITLE
Add pyroscope to homebrew-core

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#156]
### Summary
Currently we have a separate repo and people install pyroscope via a tap: 
```
brew install pyroscope-io/brew/pyroscope
```

This is great but it would be even better if they could just do:
```
brew install pyroscope
```

I think we're big enough at this point that we can be added to homebrew core. This will make the installation simpler and makes us look more legit. 

### TODO

* [ ] go through the process of adding [pyroscope to homebrew](https://docs.brew.sh/Adding-Software-to-Homebrew)
* [ ] update release scripts (talk to @petethepig about this) to trigger a github action to create a PR against the homebrew-core repo.
* [ ] make sure both our tap and the homebrew-core versions work properly (once we have the formula in homebrew-core repo we can set up some github action to basically make our tap a mirror of that formula I think)
* [ ] add linux support? I saw people using that recently, e.g [here](https://github.com/pyroscope-io/homebrew-brew/issues/1)
* [ ] set up a smoke test that would run `brew bottle` for each commit, ensuring that it's not failing (this is important because we often make changes to the build process and it's important to have tests that ensure everything is still working)
