### ISSUE TITLE
Merge grafana/phlare repo into grafana/pyroscope

### ISSUE THREAD

**Issue by simonswine** [grafana/pyroscope#2010]
## Problem
End-Users, contributors and developers face a fair bit of confusion with the two projects and especially the wording of the Phlare README is misleading

## Goals
* Keep commit history intact
* Ensure commit messages that reference to issues and PRs stay correct (Avoid that #123 in a message from grafana/phlare will link to a different PR in the grafana/pyroscope repo)
* Do not loose the stars
* Be able to release OG and Pyroscope weeklies

### Phase 1

* [x] Script to do the merge of the repos: https://github.com/grafana/phlare/pull/808 

### Phase 2: Move repo atomically 

* [x] Run the script on 2023-07-18 13:00 UTC, ensure PRs no longer can be merged into grafana/phlare, make Grafana Pyroscope available in the `next` branch, switch default branch to next.

```[tasklist]
### Phase 3
- [x] Improve README.md in both projects.
- [ ] https://github.com/grafana/pyroscope/issues/2000
- [x] Rename phlare binaries to pyroscope https://github.com/grafana/pyroscope/pull/2023
- [ ] https://github.com/grafana/pyroscope/issues/2149
- [ ] @petethepig  Clean up the `og/` folder, decide what to keep what to remove and what to move out.
- [ ] Determine the future of the `pyroscope` subcommands. (currently phlare only supports `pyroscope server`)
- [ ] https://github.com/grafana/pyroscope/issues/2151
- [x] Ensure the `make generate` works again @cyriltovena https://github.com/grafana/pyroscope/pull/2140
- [x] Fix weekly builds @simonswine
- [ ] tag api/ and ebpf/ folder
- [ ] Merge and/or rename helm chart for pyroscope and phlare
- [x] [Update MAINTAINERS.md](https://github.com/grafana/pyroscope/pull/2155)
```

```[tasklist]
### Phase 4
* [ ] [Update examples](https://github.com/grafana/pyroscope/issues/2188)
* [ ]  The `og/` folder has disappeared
* [ ] No code imports of github.com/pyroscope-io/pyroscope anmymore
* [ ] First release of Grafana Pyroscope
```

**Comment by petethepig** [comment]
Little update from me, I deleted some things from `/og` directory, and started figuring out what to do with go packages (I will move some that we use and delete the rest).
