### ISSUE TITLE
Move grafana/phlare docker image to grafana/pyroscope

### ISSUE THREAD

**Issue by simonswine** [grafana/pyroscope#2149]
```[tasklist]
### Tasks
- [x] Request docker image and permission for the CI users
- [ ] Adapt makefile
- [ ] Adapt weekly release in grafana/release
- [ ] Ensure we build main in docker hub instead of GCR
- [ ] https://github.com/grafana/pyroscope/pull/2158
- [ ] https://github.com/grafana/release/pull/312
```

**Comment by simonswine** [comment]
cc @cyriltovena
