### ISSUE TITLE
[DOC] [EPIC] Update the language SDK docs

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/pyroscope#2775]
Update files in this section: https://grafana.com/docs/pyroscope/latest/configure-client/language-sdks/ 

Landing page for SDKs is short and succinct. 

There are some overall changes that could benefit all of the language SDK pages, so I'll list them here. Keep in mind, that for all of the pages the same stylistic changes (like sentence case) apply to all of the pages even if not called out. 

The language SDKs are listed in alphabetical order. Is there any order preference or does that matter? 

Instead of using headings like "How to...", remove the "how to" so "How to add Golang profiling to your application" becomes "Add Golang profiling to your application." 

For all of the language SDK topics: 

- Add a sentence or two for an introduction. Maybe link to the official SDK site as a reference for user. 
- Use a consistent page structure. You have a start on this for some of the SDK languages. Each language SDK topic should have parallel heading structure whenever possible. Is there a consistent set of headings that apply to all SDKs? For example: 
- Before you begin
- Add {language} profiling to your application
- Configure the {language} client
- Add profiling labels to your application
- Send data to Pyroscope 
```[tasklist]
### Tasks
- [ ] Update Go SDK doc
- [ ] Update Java SDK doc
- [ ] Update .NET SDK doc
- [ ] Update Python SDK doc
- [ ] Update Ruby SDK doc
- [ ] Update Rust SDK doc
- [ ] Update NodeJS SDK doc
```

**Comment by petethepig** [comment]
working on this
