### ISSUE TITLE
[DOC] Restructure / Refine new profiling docs

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#2794]
In https://github.com/grafana/pyroscope/pull/2747 I merged things in a little bit of a "halfway" state. 

@knylander-grafana had some recommendations about reorganizing but I didn't want the PR to go stale and also wanted to see what it looked like in the sidebar before reshuffling things around

![image](https://github.com/grafana/pyroscope/assets/23323466/27122a47-5265-484c-80a0-3325657150c4)

The three files in question are 

- docs/sources/why-use-continuous-profiling/_index.md
- docs/sources/analyzing-profiles-in-pyroscope-ui/_index.md
- docs/sources/profiling-types-in-pyroscope/_index.md

Related: 
* https://github.com/grafana/pyroscope/pull/2828: This PR adds the analyze and ingest data section and moves the analyze profiles in pyroscope and profiling types in pyroscope to this new folder

```[tasklist]
### Tasks
- [x] Write draft content (https://github.com/grafana/pyroscope/pull/2747)
- [ ] https://github.com/grafana/pyroscope/issues/2736
- [ ] https://github.com/grafana/pyroscope/issues/2737
- [ ] https://github.com/grafana/pyroscope/issues/2770
- [ ] https://github.com/grafana/pyroscope/issues/2776
```

**Comment by knylander-grafana** [comment]
@Rperry2174 I'll tackle this issue during the sprint next week.

**Comment by knylander-grafana** [comment]
Related: https://github.com/grafana/pyroscope/pull/2828

**Comment by knylander-grafana** [comment]
PR for some of this content: https://github.com/grafana/pyroscope/pull/2839
