### ISSUE TITLE
[DOC] Update Pyroscope for Agent > Alloy

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/pyroscope#3271]
Update the Pyroscope documentation to use Alloy examples since Agent is being deprecated. 

Related: https://github.com/grafana/pyroscope/issues/3277

SME: Marc S

Remove Agent content and use Alloy instead. 

# Page updates

Configure the client . Grafana Agent
https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/

* Change page to be Alloy or Agent

**Set up Go profiling in pull mode**
On https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent

Install Grafana Agent section:

Add > Install Grafana Alloy > https://grafana.com/docs/alloy/latest/get-started/install/

Prepare configuration file
Alloy - config file can be anything .alloy 
Blocks should stay the same for Agent flow and Alloy. 

 **Start Grafana Agent Flow**
Start a local Pyroscope instance for testing purposes (stays the same)

 `docker run -p 4040:4040 grafana/pyroscope`

Start the collector

Start Grafana Alloy: alloy run <configuration-file.file> 
Start Grafana Agent:  grafana-agent-flow run configuration.river

Open a browser to http://localhost:4040. The page should list profiles.

### eBPF 
k8s install -- see https://grafana.com/docs/alloy/latest/get-started/install/kubernetes/ 

All ebpf docs: 
* Updates to configuration files and specifics for agent vs alloy
* Update links to Alloy and Agent

```[tasklist]
### Tasks
- [x] Update Grafana Agent index page
- [x] Update Set up Go profiling in pull mode
- [x] Update Profiling Java using the Grafana Agent
- [x] Update Profiling with eBPF index
- [x] Update Profiling with eBPF K8s
- [x] Update Profiling with eBPF Linux
- [x] Update Profiling with eBPF Docker
- [x] Update Profiling with eBPF config reference
- [x] Update Profiling with eBPF Troubleshooting
- [ ] Update sampling scrape targets
- [ ] Helm chart doc updates, refer to https://github.com/grafana/pyroscope/pull/3381
```

**Comment by knylander-grafana** [comment]
This change will disable the agent by default and enable alloy instead.

Fixes https://github.com/grafana/pyroscope/issues/3282

This is breaking change for all helm chart users.

It is required that their custom options are either migrated by replacing agent with alloy or they maintain the previous behaviour by agent.enabled: true alloy.enable: false

**Comment by knylander-grafana** [comment]
Feedback from Ashley for the install docs for Pyroscope based on a customer's feedback: 

- grafana agent referenced frequently which confused the prospect
- as a suggestion, it would be easier if the components were named the same so as we're copy/pasting from the different sections it will work without changes
  - EX - all the full examples in [this page](https://grafana.com/docs/pyroscope/next/configure-client/grafana-agent/java/#send-data-to-grafana-cloud-profiles) have a local pyro as the write output (even though its called send to cloud), but if you copy the cloud profiles config at the top this component is called endpoint while the rest of the sample config writes to example
- [this page](https://grafana.com/docs/pyroscope/next/configure-client/grafana-agent/ebpf/setup-kubernetes/) references and installs the grafana agent, not alloy - is it intentional? with a new prospect they have already installed alloy, so this is confusing if they want to just add the relevant config lines and also agent is being deprecated soon
-  I think it would be helpful to have a tab answering 'what if im running opentelemetry collector' since this is what most (of my) prospects are using
- it would be helpful if the helm chart or instructions to install alloy were at the beginning of the instructions, since it doesn't list as a pre req that you need to first install it
- from the cloud profiles doc when you start to follow the instructions to configure it brings you to the oss docs. So my prospect clicked into "Deploy on K8s" thinking it would be what he needed, but these are instructions to deploy actual pyro.

**Comment by knylander-grafana** [comment]
Additional update: 

https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/go_pull/
 
This page does not mention that the default Alloy configuration uses
annotations to control discovery of targets. So to enable
scraping/collection you also have to annotate the target pods with
annotations like [profiles.grafana.com/goroutine.scrape=true](http://profiles.grafana.com/goroutine.scrape=true)

**Comment by knylander-grafana** [comment]
PR: https://github.com/grafana/pyroscope/pull/3621/files
