### ISSUE TITLE
[DOC] Update Cloud Profiles docs for Agent > Alloy

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/pyroscope#3277]
Review the Pyroscope and Cloud Profiles documentation to use Alloy instead of Agent. 

Reference: https://github.com/grafana/pyroscope/pull/3272, https://github.com/grafana/pyroscope-squad/issues/102

```[tasklist]
### Tasks
- [x] Review existing documentation to see which pages reference Agent, include the set up and any config pages.
- [x] Are example configs in static or flow (river)?
- [ ] Update set up pages
- [x] Update other pages
- [ ] Verify with the Alloy writer
```

**Comment by knylander-grafana** [comment]
Data sources for profiles: 

Cloud Profiles needs to be update: 

1 - Sending profiles when you add a new Pyroscope data source still references Agent in the text and in the diagram. For example, https://grafana.com/orgs/kimnylander/hosted-profiles/366725#sending-profiles

![Image](https://github.com/user-attachments/assets/2dbf9b9e-9929-4efe-b357-859d426df099)

2 - Hosted profiles data source is up to date. 

![Image](https://github.com/user-attachments/assets/d3228518-94b2-4e4b-b111-16fb766698d3)

3 - Pyroscope data source is okay. The text for the steps has been updated to match the newer UI for 11.2 and in Cloud.

**Comment by knylander-grafana** [comment]
The landing/start page for Explore Profiles needs to be updated to use Alloy instead of Agent. Issue: https://github.com/grafana/explore-profiles/issues/226
